export const workStatusMockData = [
  {
    id: "1",
    userId: "2",
    taskName: "Make api for Task Table",
    taskDescription: "Create an api for workStatus Data",
    taskStatus: "Assigned",
    assignedBy: "Manager",
    assignedTimeStamp: "29/07/2022",
    completedTimeStamp: "On progress",
  },
  {
    id: "2",
    userId: "2",
    taskName: "create form for Work Status",
    taskDescription: "Create a form to save work status details",
    taskStatus: "Assigned",
    assignedBy: "Manager",
    assignedTimeStamp: "28/07/2022",
    completedTimeStamp: "On progress",
  },
  {
    id: "3",
    userId: "2",
    taskName: "create form for Work Status",
    taskDescription: "Create a form to save work status details",
    taskStatus: "Assigned",
    assignedBy: "Manager",
    assignedTimeStamp: "28/07/2022",
    completedTimeStamp: "On progress",
  },
  {
    id: "4",
    userId: "2",
    taskName: "create form for Work Status",
    taskDescription: "Create a form to save work status details",
    taskStatus: "Assigned",
    assignedBy: "Manager",
    assignedTimeStamp: "28/07/2022",
    completedTimeStamp: "On progress",
  },
];
